# Generated by Django 4.1.2 on 2023-02-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_recipe_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
