# Generated by Django 4.1.2 on 2023-02-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_delete_ingredient_delete_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
